tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "ansible"
brew "coreutils"
brew "git"
brew "jq"
brew "neovim"
brew "nkf"
brew "nodebrew"
brew "mas"
brew "peco"
brew "pyenv"
brew "saml2aws"
brew "tfenv"
brew "tig"
brew "tree"
brew "yq"

cask_args appdir: "~/Applications"

cask "appcleaner"
cask "clipy"
cask "docker"
cask "evernote"
cask "firefox"
cask "gather"
cask "google-drive"
cask "google-chrome"
cask "hyper"
cask "iterm2"
cask "microsoft-teams"
cask "skitch"
cask "slack"
cask "the-unarchiver"
cask "visual-studio-code"
cask "zoom"

mas "Perculia", id: 1462633284
