- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
    homebrew_packages:
      - { name: readline }
      - { name: sqlite }
      - { name: gdbm }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: libyaml }
      - { name: ansible }
      - { name: vim }
      - { name: git }
      - { name: tig }
    homebrew_cask_packages:
      - { name: java }
      - { name: iterm2 }
      - { name: alfred }
      - { name: google-chrome }
      - { name: google-drive }
      - { name: google-japanese-ime }
      - { name: evernote }
      - { name: virtualbox }
      - { name: vagrant }
      - { name: android-studio }
      - { name: android-file-transfer }
      - { name: genymotion }
      - { name: gimp }

  tasks:
    - name: enable homebrew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install homebrew packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: create directory of brew info
      file: path=brew_info state=directory
    - name: save brew info
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    - name: install brew-cask
      homebrew: name=brew-cask state=latest
    - name: install cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: create directory of brew-cask info
      file: path=cask_info state=directory
    - name: save brew-cask info
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list


