---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    pip_packages:
      - { name: awscli }
      - { name: awslogs }
      - { name: pipenv }
      - { name: autopep8 }
      - { name: flake8 }
      - { name: pytest-jsonlint }
    vscode_extension_list:
      - { name: vscodevim.vim }
      - { name: marp-team.marp-vscode }
      - { name: yzane.markdown-pdf }
      - { name: yzhang.markdown-all-in-one }
      - { name: hediet.vscode-drawio }
  tasks:
    - name: install pip packages
      pip: name={{ item.name }} executable=pip3 state=present
      with_items: "{{ pip_packages }}"

    - name: install vscode extensions
      shell: code --install-extension {{ item.name }}
      with_items: "{{ vscode_extension_list }}"
